### ISSUE TITLE
Rename 'master' branches to 'main'

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/governance#7]
I suggest we rename our 'master' branches to 'main' (or 'default'). 

The term master, with its association to slavery, is offensive to many people. As a name, it is no more descriptive or useful than the more neutral alternatives. I don't believe that renaming will create any significant issues for MDS users or contributors.

For more on the topic:
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by schnuerle** [comment]
Agree and since this legitimate issue has come up again recently, I've been thinking of what we need to do for the OMF.  Every existing repo can be changed without any impact, except for `mobility-data-specification`. And the only real issues there are documentation and files that reference master within the repo code itself - it's usually not changed until a release.  However, we could just hotfix it and I wouldn't see a problem with doing that.

I had been waiting for Github to put something in place that could setup an automatic redirect, so if a web/social media/external/issue/PR link used master in the URL it could auto redirect to main.  Maybe that will come but I think we should still move forward.  Today seems to be a good day to do it.  I'll start with the easy repos first and report back.

**Comment by schnuerle** [comment]
I've updated these repos to use main:

- governance
- mds-audit
- mds-compliance-mobile
- privacy-committee
- .github

What's left are 

- mds-core
- mobility-data-specification

I want to check with @avatarneil and @karcass about the impacts to `mds-core` as they were working on reconciling their updates to the OMF repo.

And I'll talk to @thekaveman about steps to update `mobility-data-specification` accounting for all impacts.

**Comment by johnclary** [comment]
i support y'all doing this.

i've had a lot of discussion about this with my team, and there's definitely a debate to be had about whether the git use of `master` is actually drawing on the `master`/`slave` dichotomy. 

but at the end of the day we agreed that, regardless of intent, master is a triggering term and there are plenty of other words we can use in its stead.

unfortunately, this presents significant breaking changes to our CI, so it's going to be a while before we take action.

**Comment by schnuerle** [comment]
`mds-core` is done.  Working on how to handle all the parts of `mobility-data-specification`.

**Comment by schnuerle** [comment]
`mobility-data-specification` is now done.  'main' is the new default branch.  

'master' still exists for use by active external applications, schema validators, and direct links in some city policy documents and other websites.  The hope is to delete it in the release after next once we have given people time to update their references to it and releases prior to 1.0.0 are no longer supported.

Existing releases like 0.4.1 are immutable and still reference master, but future releases will not.

There is a pull request now pending approvals to update 'dev' with the changes needed to erase references to 'master'. https://github.com/openmobilityfoundation/mobility-data-specification/pull/522

**Comment by schnuerle** [comment]
The full request is merged now, updating references to 'main' in the 'dev' branch.  OMF website links are updated too.  

We will add a wiki page later to the MDS repo later with 1.0.0 explaining things that are still connected to the depreciated 'master' branch (providers.csv file, JSON schema, city policy links) with some guidance for people on how to update.
